name: expiry_watch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  build_runner: ^2.11.1
  drift: ^2.31.0
  drift_dev: ^2.31.0
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  image_picker: ^1.2.1
  sqlite3_flutter_libs: ^0.5.41
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png
